Repository boostcamp-2020/Project11-C-Web-FE-Performance-Monitoring-Admin, pull requests merged in 2020-12, with the labels that each got.

#8 Admin Main Page 틀 생성
  .eslintrc
  package-lock.json
  package.json
  src/App.tsx
  src/components/login/Input.tsx
  src/components/login/OauthButton.tsx
  src/components/login/SignButton.tsx
  src/components/login/Text.tsx
  src/components/main/NavBar.tsx
  src/components/main/ProjectDetail.tsx
  src/components/main/ProjectSniffet.tsx
  src/index.tsx
  src/pages/Login.tsx
  src/pages/Main.tsx
  style/globalStyle.ts
  tsconfig.json
  webpack.config.js
Labels: feature, frontend

#10 login front 수정
  src/components/login/OauthButton.tsx
  src/pages/Login.tsx
Labels: feature, frontend

#11 로그인 화면 구현
  .babelrc
  package-lock.json
  package.json
  public/index.html
  public/svg/circle.svg
  public/svg/fractal_25.svg
  src/App.tsx
  src/components/login/Input.tsx
  src/components/login/LeftContents.tsx
  src/components/login/OauthButton.tsx
  src/components/login/RightContents.tsx
  src/components/login/SignButton.tsx
  src/components/login/Text.tsx
  src/components/main/NavBar.tsx
  src/components/main/ProjectDetail.tsx
  src/components/main/ProjectSniffet.tsx
  src/components/projects/LeftBar.tsx
  src/components/projects/MainContainer.tsx
  src/components/utils/Header.tsx
  src/index.tsx
  src/pages/Login.tsx
  src/pages/Main.tsx
  src/pages/Projects.tsx
  src/style/globalStyle.ts
  webpack.config.js
Labels: feature, frontend

#13 Projects 페이지 구현
  babel.config.js
  package-lock.json
  package.json
  public/index.html
  src/App.tsx
  src/components/Issues/LeftBar.tsx
  src/components/common/Chart.tsx
  src/components/projects/ProjectCard.tsx
  src/pages/ProjectDetail.tsx
  src/pages/ProjectNew.tsx
  src/pages/Projects.tsx
  src/style/globalStyle.ts
  src/utils/Api.ts
  tsconfig.json
  webpack.config.js
  yarn.lock
Labels: feature, frontend

#16 프로젝트 생성 페이지 추가
  package.json
  public/png/Express.png
  public/png/JavaScript.png
  public/png/Node.png
  public/png/React.png
  public/png/Vue.png
  src/App.tsx
  src/components/project-new/Platform.tsx
  src/components/project-new/Platforms.tsx
  src/components/project-new/ProjectForm.tsx
  src/components/projects/ProjectCard.tsx
  src/pages/ProjectNew.tsx
  src/pages/Projects.tsx
  src/pages/Usage.tsx
  src/utils/Api.ts
  src/utils/Interface.ts
  yarn.lock
Labels: feature, frontend

#34 로그인 화면 디자인 수정 및 유효성 검사
  src/components/login/RightContents.tsx
Labels: feature, frontend

#40 회원가입/로그인 입력 유효 값 처리
  src/components/login/RightContents.tsx
Labels: feature, frontend

#41 해결-담당자 기능 추가 구현, 이슈 디테일 화면 추가 구현, 기타 버그 수정
  public/png/apple.png
  public/png/chrome.png
  public/png/congratulations.png
  public/png/edge.png
  public/png/firefox.png
  public/png/linux.png
  public/png/nodeIcon.png
  public/png/opera.png
  public/png/run_color.png
  public/png/safari.png
  public/png/ubuntu.png
  public/png/unknown.png
  public/png/unkown.png
  public/png/window.png
  src/App.tsx
  src/Test.tsx
  src/components/Issues/MainContainer.tsx
  src/components/Issues/context/ResolveProvider.tsx
  src/components/Issues/detail/ErrorEvent/ErrorEventInfo.tsx
  src/components/Issues/detail/ErrorEvent/MainPoint.tsx
  src/components/Issues/detail/ErrorEvent/StackItem.tsx
  src/components/Issues/detail/ErrorEvent/TagArea.tsx
  src/components/Issues/detail/Header/DetailHeader.tsx
  src/components/Issues/detail/MainContainer.tsx
  src/components/Issues/detail/TagArea.tsx
  src/components/Issues/issue/Assigned.tsx
  src/components/Issues/issue/Filter.tsx
  src/components/Issues/issue/IssueItem.tsx
  src/components/Issues/issue/TableColumn.tsx
  src/components/common/Header.tsx
  src/components/common/NoticeEmpty.tsx
  src/components/login/RightContents.tsx
  src/components/utils/DateHelper.tsx
  src/components/utils/Graph.tsx
  src/index.tsx
  src/pages/IssueDetail.tsx
  src/pages/Issues.tsx
  src/pages/Login.tsx
  src/pages/Projects.tsx
Labels: bug, feature, frontend

#42 alert list page 기본 구현
  src/App.tsx
  src/components/Alerts/AlertList.tsx
  src/components/Issues/LeftBar.tsx
  src/pages/Alerts.tsx
  src/utils/AlertApi.ts
Labels: feature, frontend

#43 가이드 구현(docs) 및 컨텍스트 적용, 기타 디자인 수정 및 버그 수정
  public/png/Express.png
  public/png/Node.png
  public/png/React.png
  public/png/nodeIcon.png
  src/App.tsx
  src/components/Issues/MainContainer.tsx
  src/components/Issues/detail/ErrorEvent/MainPoint.tsx
  src/components/Issues/detail/MainContainer.tsx
  src/components/Issues/issue/IssueItem.tsx
  src/components/Issues/issue/TableColumn.tsx
  src/components/common/Header.tsx
  src/components/common/LeftBar.tsx
  src/components/common/UserContainer.tsx
  src/components/docs/DocsMain.tsx
  src/components/docs/describe/guideInfo.tsx
  src/components/docs/nav/PlatformItem.tsx
  src/components/docs/nav/PlatformNav.tsx
  src/components/project-new/Platform.tsx
  src/components/project-new/Platforms.tsx
  src/components/projects/ProjectCard.tsx
  src/components/tutorial/TutorialStepper.tsx
  src/context/PositionProvider.tsx
  src/context/ResolveProvider.tsx
  src/pages/DocsPage.tsx
  src/pages/IssueDetail.tsx
  src/pages/Issues.tsx
  src/pages/ProjectNew.tsx
  src/pages/Projects.tsx
  src/pages/Tutorial.tsx
Labels: bug, feature, frontend

#44 Stats 페이지 구현
  package.json
  src/App.tsx
  src/components/common/Chart.tsx
  src/components/stats/DailyErrorChart.tsx
  src/components/stats/IssuePieChart.tsx
  src/components/stats/ResolveGaugeChart.tsx
  src/components/stats/TagBarChart.tsx
  src/pages/ProjectDetail.tsx
  src/pages/ProjectNew.tsx
  src/pages/Projects.tsx
  src/pages/Stats.tsx
  src/utils/Api.ts
  yarn.lock
Labels: feature, frontend

#49 alert list page UI개선, Link 오류 수정
  src/components/Alerts/AlertList.tsx
Labels: enhancement, frontend

#61 필터 기능 구현, 컨텍스트 추가, 버그 수정
  src/App.tsx
  src/components/Issues/MainContainer.tsx
  src/components/Issues/detail/MainContainer.tsx
  src/components/Issues/issue/Filter.tsx
  src/components/Issues/issue/IssueItem.tsx
  src/components/Issues/issue/SearchButton.tsx
  src/components/Issues/issue/SortButton.tsx
  src/components/Issues/issue/TableColumn.tsx
  src/components/common/LeftBar.tsx
  src/components/common/UserContainer.tsx
  src/components/projects/ProjectCard.tsx
  src/context/IssuesProvider.tsx
  src/context/PositionProvider.tsx
  src/context/UserProvider.tsx
  src/pages/Alerts.tsx
  src/pages/Issues.tsx
  src/pages/Projects.tsx
  src/pages/Stats.tsx
Labels: bug, feature, frontend

#62 Sign up, sign in, sign out 구현, api 요청 부분 리팩토링
  src/components/Issues/detail/Header/DetailHeader.tsx
  src/components/Issues/detail/MainContainer.tsx
  src/components/Issues/issue/Assigned.tsx
  src/components/Issues/issue/IssueItem.tsx
  src/components/Issues/issue/TableColumn.tsx
  src/components/common/Header.tsx
  src/components/common/LeftBar.tsx
  src/components/common/SignInModal.tsx
  src/components/login/RightContents.tsx
  src/context/IssuesProvider.tsx
  src/context/PositionProvider.tsx
  src/context/UserProvider.tsx
  src/pages/Projects.tsx
  src/utils/Api.ts
  src/utils/Interface.ts
Labels: feature, frontend
